# Generated by Django 3.0.6 on 2020-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20200506_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scan',
            name='finish_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='location',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scan',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
