# Generated by Django 3.0.6 on 2020-05-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_auto_20200506_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
