# Generated by Django 3.0.6 on 2020-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_auto_20200506_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='in_progress',
        ),
        migrations.AddField(
            model_name='scan',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
