# Generated by Django 3.0.6 on 2020-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_auto_20200507_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scan',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
