# Generated by Django 3.0.6 on 2020-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_auto_20200508_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, default='autodetect', max_length=255),
        ),
    ]
