# Generated by Django 3.0.6 on 2020-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_auto_20200509_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='host',
            new_name='hostname',
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('mac', models.CharField(blank=True, max_length=255)),
                ('vlan', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('access_devices', models.ManyToManyField(to='scans.Device')),
            ],
        ),
    ]
