# Generated by Django 3.0.6 on 2020-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_auto_20200511_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='scans_found',
            field=models.ManyToManyField(to='scans.Scan'),
        ),
    ]
