# Generated by Django 3.0.6 on 2020-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0012_host_scans_found'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='id',
            new_name='uuid',
        ),
    ]
