# Generated by Django 3.0.6 on 2020-05-18 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_auto_20200511_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='access_devices',
        ),
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mac',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('mac', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scans.Device')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='access_interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.Interface'),
        ),
    ]
