# Generated by Django 3.0.6 on 2020-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_auto_20200518_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='access_interface',
        ),
        migrations.AddField(
            model_name='host',
            name='access_interface',
            field=models.ManyToManyField(to='scans.Interface'),
        ),
    ]
